"""update_order

Revision ID: 17852d24b3db
Revises: b5e977749ce8
Create Date: 2026-02-18 18:19:16.438395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17852d24b3db'
down_revision: Union[str, Sequence[str], None] = 'b5e977749ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('order_product_id', 'order_products', ['order_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_product_id', 'order_products', type_='unique')
    # ### end Alembic commands ###
