"""update_order_products2

Revision ID: 3b62454efd71
Revises: b9a2ea1c7a41
Create Date: 2026-02-18 19:03:48.550169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b62454efd71'
down_revision: Union[str, Sequence[str], None] = 'b9a2ea1c7a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_products', 'order_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_products', 'order_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
