"""add_order

Revision ID: 95974c94441b
Revises: 759f8d41e6ca
Create Date: 2026-02-16 18:25:43.562536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95974c94441b'
down_revision: Union[str, Sequence[str], None] = '759f8d41e6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_characteristics', 'name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('product_characteristics', 'value',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_constraint(op.f('product_characteristics_name_key'), 'product_characteristics', type_='unique')
    op.drop_constraint(op.f('product_characteristics_value_key'), 'product_characteristics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('product_characteristics_value_key'), 'product_characteristics', ['value'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('product_characteristics_name_key'), 'product_characteristics', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_characteristics', 'value',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('product_characteristics', 'name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
