"""update_order_products

Revision ID: b9a2ea1c7a41
Revises: 17852d24b3db
Create Date: 2026-02-18 19:02:52.517752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a2ea1c7a41'
down_revision: Union[str, Sequence[str], None] = '17852d24b3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_products_order_id_fkey'), 'order_products', type_='foreignkey')
    op.create_foreign_key(None, 'order_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.create_foreign_key(op.f('order_products_order_id_fkey'), 'order_products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
